/**
 * messages.ts — Minimal LangChain-compatible message types.
 *
 * Covers all standard message roles used by chat models:
 *   human, ai, system, tool, function (legacy).
 */

// ---------------------------------------------------------------------------
// Content types
// ---------------------------------------------------------------------------

/** A single text or multimodal content block. */
export type ContentBlock =
  | string
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: { url: string; detail?: string } }
  | { type: "tool_use"; id: string; name: string; input: unknown }
  | { type: "tool_result"; tool_use_id: string; content: MessageContent };

/** The content of a message — either a plain string or an array of blocks. */
export type MessageContent = string | ContentBlock[];

// ---------------------------------------------------------------------------
// Tool calls
// ---------------------------------------------------------------------------

/** A structured tool call produced by an AI message. */
export interface ToolCall {
  /** Unique identifier for this call (used to correlate with ToolMessage). */
  id: string;
  /** Name of the tool to invoke. */
  name: string;
  /** Parsed arguments object. */
  args: Record<string, unknown>;
  /** Raw JSON string of args (as returned by the model). */
  argsRaw?: string;
}

/** A streaming chunk of a tool call being built incrementally. */
export interface ToolCallChunk {
  index: number;
  id?: string;
  name?: string;
  argsRaw?: string;
}

/** A tool call that could not be parsed correctly. */
export interface InvalidToolCall {
  id?: string;
  name?: string;
  argsRaw?: string;
  error: string;
}

// ---------------------------------------------------------------------------
// Usage / metadata
// ---------------------------------------------------------------------------

/** Token-usage information returned by the model. */
export interface UsageMetadata {
  input_tokens?: number;
  output_tokens?: number;
  total_tokens?: number;
}

// ---------------------------------------------------------------------------
// Base message
// ---------------------------------------------------------------------------

/** All possible message roles. */
export type MessageRole = "human" | "ai" | "system" | "tool" | "function";

/** Common fields shared by every message type. */
export interface BaseMessageFields {
  content: MessageContent;
  name?: string;
  id?: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  additional_kwargs?: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  response_metadata?: Record<string, any>;
}

/** Base class for all messages. */
export abstract class BaseMessage {
  abstract readonly type: MessageRole;

  content: MessageContent;
  name?: string;
  id?: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  additional_kwargs: Record<string, any>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  response_metadata: Record<string, any>;

  constructor(fields: MessageContent | BaseMessageFields) {
    if (typeof fields === "string" || Array.isArray(fields)) {
      this.content = fields;
      this.additional_kwargs = {};
      this.response_metadata = {};
    } else {
      this.content = fields.content ?? "";
      this.name = fields.name;
      this.id = fields.id;
      this.additional_kwargs = fields.additional_kwargs ?? {};
      this.response_metadata = fields.response_metadata ?? {};
    }
  }

  getType(): MessageRole {
    return this.type;
  }

  /** Return the text content of the message (joining all text blocks). */
  getText(): string {
    if (typeof this.content === "string") return this.content;
    return this.content
      .map((b) => (typeof b === "string" ? b : "text" in b ? b.text : ""))
      .join("");
  }
}

// ---------------------------------------------------------------------------
// Concrete message classes
// ---------------------------------------------------------------------------

/** A message from the human/user. */
export class HumanMessage extends BaseMessage {
  readonly type = "human" as const;

  static isInstance(obj: unknown): obj is HumanMessage {
    return obj instanceof HumanMessage;
  }
}

/** Additional fields available on AI messages. */
export interface AIMessageFields extends BaseMessageFields {
  tool_calls?: ToolCall[];
  invalid_tool_calls?: InvalidToolCall[];
  usage_metadata?: UsageMetadata;
}

/** A message generated by the AI/model. */
export class AIMessage extends BaseMessage {
  readonly type = "ai" as const;

  tool_calls: ToolCall[];
  invalid_tool_calls: InvalidToolCall[];
  usage_metadata?: UsageMetadata;

  constructor(fields: MessageContent | AIMessageFields) {
    super(fields as MessageContent | BaseMessageFields);
    if (typeof fields === "string" || Array.isArray(fields)) {
      this.tool_calls = [];
      this.invalid_tool_calls = [];
    } else {
      this.tool_calls = fields.tool_calls ?? [];
      this.invalid_tool_calls = fields.invalid_tool_calls ?? [];
      this.usage_metadata = fields.usage_metadata;
    }
  }

  static isInstance(obj: unknown): obj is AIMessage {
    return obj instanceof AIMessage;
  }
}

/** A system / instruction message (typically the first in a conversation). */
export class SystemMessage extends BaseMessage {
  readonly type = "system" as const;

  static isInstance(obj: unknown): obj is SystemMessage {
    return obj instanceof SystemMessage;
  }
}

/** Additional fields for tool result messages. */
export interface ToolMessageFields extends BaseMessageFields {
  tool_call_id: string;
}

/** The result returned after executing a tool. */
export class ToolMessage extends BaseMessage {
  readonly type = "tool" as const;

  tool_call_id: string;

  constructor(fields: ToolMessageFields) {
    super(fields);
    this.tool_call_id = fields.tool_call_id;
  }

  static isInstance(obj: unknown): obj is ToolMessage {
    return obj instanceof ToolMessage;
  }
}

// ---------------------------------------------------------------------------
// Streaming chunk types
// ---------------------------------------------------------------------------

/** Streaming chunk of an AI message produced during generation. */
export class AIMessageChunk extends BaseMessage {
  readonly type = "ai" as const;

  tool_call_chunks: ToolCallChunk[];
  tool_calls: ToolCall[];
  invalid_tool_calls: InvalidToolCall[];
  usage_metadata?: UsageMetadata;

  constructor(
    fields:
      | MessageContent
      | (BaseMessageFields & {
          tool_call_chunks?: ToolCallChunk[];
          tool_calls?: ToolCall[];
          invalid_tool_calls?: InvalidToolCall[];
          usage_metadata?: UsageMetadata;
        })
  ) {
    super(fields as MessageContent | BaseMessageFields);
    if (typeof fields === "string" || Array.isArray(fields)) {
      this.tool_call_chunks = [];
      this.tool_calls = [];
      this.invalid_tool_calls = [];
    } else {
      this.tool_call_chunks = fields.tool_call_chunks ?? [];
      this.tool_calls = fields.tool_calls ?? [];
      this.invalid_tool_calls = fields.invalid_tool_calls ?? [];
      this.usage_metadata = fields.usage_metadata;
    }
  }

  /** Concatenate two chunks during streaming aggregation. */
  concat(other: AIMessageChunk): AIMessageChunk {
    const content =
      typeof this.content === "string" && typeof other.content === "string"
        ? this.content + other.content
        : this.content;

    // Merge usage metadata
    let usage_metadata: UsageMetadata | undefined;
    if (this.usage_metadata ?? other.usage_metadata) {
      usage_metadata = {
        input_tokens:
          (this.usage_metadata?.input_tokens ?? 0) +
          (other.usage_metadata?.input_tokens ?? 0),
        output_tokens:
          (this.usage_metadata?.output_tokens ?? 0) +
          (other.usage_metadata?.output_tokens ?? 0),
        total_tokens:
          (this.usage_metadata?.total_tokens ?? 0) +
          (other.usage_metadata?.total_tokens ?? 0),
      };
    }

    // Merge tool call chunks by index
    const chunkMap = new Map<number, ToolCallChunk>();
    for (const c of [...this.tool_call_chunks, ...other.tool_call_chunks]) {
      const prev = chunkMap.get(c.index);
      if (prev) {
        chunkMap.set(c.index, {
          ...prev,
          id: c.id ?? prev.id,
          name: c.name ?? prev.name,
          argsRaw: (prev.argsRaw ?? "") + (c.argsRaw ?? ""),
        });
      } else {
        chunkMap.set(c.index, { ...c });
      }
    }

    return new AIMessageChunk({
      content,
      tool_call_chunks: [...chunkMap.values()],
      tool_calls: this.tool_calls.length ? this.tool_calls : other.tool_calls,
      invalid_tool_calls: this.invalid_tool_calls.length
        ? this.invalid_tool_calls
        : other.invalid_tool_calls,
      usage_metadata,
      response_metadata: {
        ...this.response_metadata,
        ...other.response_metadata,
      },
    });
  }
}

// ---------------------------------------------------------------------------
// Type aliases / helpers
// ---------------------------------------------------------------------------

/** Any message type. */
export type AnyMessage =
  | HumanMessage
  | AIMessage
  | SystemMessage
  | ToolMessage;

/** A tuple shorthand for building messages: [role, content]. */
export type MessageTuple = [MessageRole, MessageContent];

/** Convert a message tuple or string to a concrete message object. */
export function coerceMessageLike(
  input: AnyMessage | MessageTuple | string
): AnyMessage {
  if (input instanceof BaseMessage) return input as AnyMessage;
  if (typeof input === "string") return new HumanMessage(input);
  const [role, content] = input;
  switch (role) {
    case "human":
      return new HumanMessage(content);
    case "ai":
      return new AIMessage(content);
    case "system":
      return new SystemMessage(content);
    case "tool":
      throw new Error(
        "Use ToolMessage directly — tool_call_id is required."
      );
    default:
      throw new Error(`Unknown role: ${role}`);
  }
}
